# Generated by Django 3.0.6 on 2020-05-31 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='activity_periods',
        ),
    ]
