# Generated by Django 3.0.6 on 2020-05-31 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapi', '0002_remove_product_activity_periods'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='activity_periods',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
